# Generated by Django 4.2.6 on 2024-01-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailinginfo",
            name="subject",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="emailinginfo",
            name="timeStamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailinginfo",
            name="message",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="emailinginfo",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
