# Generated by Django 4.2.6 on 2024-01-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailinginfo",
            name="message",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="emailinginfo",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
