# Generated by Django 4.2.6 on 2024-01-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_alter_emailinginfo_message_alter_emailinginfo_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailinginfo",
            name="timeStamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
